language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "pypy"
install:
  - pip install pipenv
  - pipenv install
before_script:
  - SECRET_KEY=python contrib/secret_gen.py
  - echo "DEBUG=False" >> .env
  - echo "SECRET_KEY=$SECRET_KEY" >> .env
test_script:
  - pipenv run pytest
branches:
  only:
    - master