language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "pypy"
install:
  - pip install pipenv
  - pipenv install
test_script:
  - pipenv run pytest
recipients:
  - zandorsabino@gmail.com