language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "pypy"
install:
  - cp contrib/env-sample .env
  - pip install -q -r requirements.txt
  - pip install coveralls
script:
  - coverage run --source='.' manage.py test
after_success:
  - coveralls