language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "pypy"
install:
  - pip install pipenv
  - pipenv lock
  - pipenv sync
test_script:
  - copy contrib/env-sample .env
  - pipenv run pytest
recipients:
  - zandorsabino@gmail.com