language: python
python:
  - "3.9"
install:
  - cp contrib/env-sample .env
  - pip install coveralls
  - pip install --require-hashes -r requirements.txt
  - python manage.py migrate
script:
  - coverage run --source='.' manage.py test
after_success:
  - coveralls