language: python
python:
  - "3.6"
  - "3.7"
  - "3.8"
  - "3.9"
  - "pypy"
install:
  - pip install pipenv
  - pipenv install
before_script:
  - echo "DEBUG=False" >> .env
  - echo "SECRET_KEY=IS_A_NOT_GOOD_SECRET_JUST_USE_FOR_TEST" >> .env
test_script:
  - pipenv run tests
branches:
  only:
    - master