# Generated by Django 3.1.6 on 2021-03-07 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0002_auto_20210307_1936"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="subscription",
            name="url_hash",
        ),
    ]
