# Generated by Django 3.1.6 on 2021-03-29 21:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0003_remove_subscription_url_hash"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="paid",
            field=models.BooleanField(default=False),
        ),
    ]
