# Generated by Django 3.1.6 on 2021-03-29 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0004_subscription_paid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="paid",
            field=models.BooleanField(default=False, verbose_name="pago"),
        ),
    ]
