# Generated by Django 3.1.6 on 2021-03-30 02:10

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0005_auto_20210329_1846"),
    ]

    operations = [
        migrations.AddField(
            model_name="subscription",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("bdb44a09-6e6e-44aa-a9d0-c9d3dfade4ba"),
                editable=False,
                unique=True,
            ),
        ),
    ]
