# Generated by Django 3.1.6 on 2021-03-30 01:54

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('subscriptions', '0006_auto_20210329_2225'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='id',
            field=models.UUIDField(default=uuid.UUID('8e8afeb2-43ac-4e61-8c80-c9ae450770a9'), editable=False, primary_key=True, serialize=False),
        ),
    ]
