# Generated by Django 3.1.6 on 2021-04-01 18:34

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0010_auto_20210401_1514"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("1a56de68-b7a5-4636-99e4-d89f73c4dbf6"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
