# Generated by Django 3.1.6 on 2021-04-07 14:16

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0014_auto_20210405_1308"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("f1916b16-1fa3-4d93-b822-70eba4fc11ed"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
