# Generated by Django 3.1.6 on 2021-04-07 14:40

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("subscriptions", "0017_auto_20210407_1139"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="uuid",
            field=models.UUIDField(
                default=uuid.UUID("de2c279b-9eee-4eb0-8f88-91c861b7d61c"),
                editable=False,
                primary_key=True,
                serialize=False,
            ),
        ),
    ]
