# Generated by Django 3.1.6 on 2021-04-05 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_auto_20210401_1544"),
    ]

    operations = [
        migrations.CreateModel(
            name="Talk",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("start", models.TimeField()),
                ("description", models.TextField()),
                ("speakers", models.ManyToManyField(to="core.Speaker")),
            ],
        ),
    ]
