# Generated by Django 3.1.6 on 2021-04-07 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0006_auto_20210405_1308"),
    ]

    operations = [
        migrations.CreateModel(
            name="Course",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200, verbose_name="título")),
                (
                    "start",
                    models.TimeField(blank=True, null=True, verbose_name="início"),
                ),
                ("description", models.TextField(blank=True, verbose_name="descrição")),
                ("slots", models.IntegerField()),
                (
                    "speakers",
                    models.ManyToManyField(
                        blank=True, to="core.Speaker", verbose_name="palestrantes"
                    ),
                ),
            ],
            options={
                "verbose_name": "palestra",
                "verbose_name_plural": "palestras",
                "abstract": False,
            },
        ),
    ]
