# Generated by Django 3.1.6 on 2021-04-07 15:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_course_abc_to_mti"),
    ]

    operations = [
        migrations.DeleteModel(
            name="CourseOld",
        ),
    ]
